package br.gov.model.faturamento;


public enum DebitoCreditoSituacao {
	NORMAL,
	RETIFICADA,
	INCLUIDA,
	CANCELADA,
	CANCELADA_POR_RETIFICACAO,
	PARCELADA,
	ARRASTADA,
	ENTRADA_DE_PARCELAMENTO,
	PAGA_OU_PRESCRITO,
	PRE_FATURADA,
	CARTAO_CREDITO,
	ERRO_PROCESSAMENTO,
	DEBITO_PRESCRITO_CONTAS_INCLUIDAS;
}
